export const LSM_HOOKS = [
  { name: 'security_file_open', group: 'Files & Paths', risk: 'high',
    desc: 'LSM hook on file open — sensitive-path access even when open/openat is bypassed (io_uring, direct VFS).',
    backstops: ['open', 'openat', 'openat2', 'io_uring'],
    toctou: 'Fires when the kernel actually opens the file. A path retargeted after the syscall-entry check (symlink or rename race) still resolves here — the event carries the real target.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' },
           { key: 'flags',    kind: 'string', label: 'open flags' }] },
  { name: 'security_inode_unlink', group: 'Files & Paths', risk: 'high',
    desc: 'LSM hook on file deletion — anti-forensics / log and artefact wiping.',
    backstops: ['unlink', 'unlinkat'],
    toctou: 'Deletion observed on the resolved inode — covers unlink-and-replace races even when the syscall layer is bypassed.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' }] },
  { name: 'security_inode_rename', group: 'Files & Paths', risk: 'high',
    desc: 'LSM hook on rename — the atomic-swap primitive of TOCTOU path races.',
    backstops: ['rename', 'renameat', 'renameat2'],
    toctou: 'rename() is the atomic-swap primitive of most filesystem TOCTOU attacks. Observed at the point of use with both real inodes.',
    args: [{ key: 'old_path', kind: 'path', label: 'old path' },
           { key: 'new_path', kind: 'path', label: 'new path' }] },
  { name: 'security_inode_symlink', group: 'Files & Paths', risk: 'high',
    desc: 'LSM hook on symlink creation — symlink redirection races against path checks.',
    backstops: ['symlink', 'symlinkat'],
    toctou: 'Drop a link where a privileged process will re-resolve a checked path. The hook sees the link and its target at creation time.',
    args: [{ key: 'linkpath', kind: 'path', label: 'link path' },
           { key: 'target',   kind: 'path', label: 'target' }] },
  { name: 'security_inode_mknod', group: 'Files & Paths', risk: 'medium',
    desc: 'LSM hook on device/special-file creation — device-node planting.',
    backstops: ['mknod', 'mknodat'],
    toctou: 'Special-file creation seen on the resolved parent inode — node planted into a checked directory is visible here.',
    args: [{ key: 'file_name', kind: 'path', label: 'path' }] },

  { name: 'security_bprm_check', group: 'Process Execution', risk: 'high',
    desc: 'LSM hook on every exec — the binary the kernel actually loads, not the path shown at syscall entry.',
    backstops: ['execve', 'execveat'],
    toctou: 'The exec gate. Swapping the file after an access() check, or execing through a racing symlink, changes nothing: the event describes the loaded file.',
    args: [{ key: 'pathname', kind: 'path', label: 'binary path' }] },

  { name: 'security_mmap_file', group: 'Memory', risk: 'high',
    desc: 'LSM hook on file-backed mmap — the file actually mapped (library injection, exec loading).',
    backstops: ['mmap', 'mmap2'],
    toctou: 'Sees the file ACTUALLY mapped, not the path that was checked — the file object is already pinned in the kernel when the hook fires.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' },
           { key: 'prot',     kind: 'string', label: 'prot' }] },
  { name: 'security_file_mprotect', group: 'Memory', risk: 'high',
    desc: 'LSM hook on mprotect — flipping mapped pages to executable (W^X violation).',
    backstops: ['mprotect', 'pkey_mprotect'],
    toctou: 'Protection flips evaluated against the real VMA inside the kernel — visible even when the syscall args were staged to look benign.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' },
           { key: 'prot',     kind: 'string', label: 'prot' }] },

  { name: 'security_socket_create', group: 'Network', risk: 'medium',
    desc: 'LSM hook on socket creation — the socket family/type the kernel set up.',
    backstops: ['socket'],
    toctou: 'Family/type observed as the kernel created the socket.',
    args: [{ key: 'family', kind: 'string', label: 'family' },
           { key: 'type',   kind: 'string', label: 'type' }] },
  { name: 'security_socket_connect', group: 'Network', risk: 'high',
    desc: 'LSM hook on outbound connect — C2 visible even when connect() is bypassed.',
    backstops: ['connect', 'io_uring'],
    toctou: 'The classic sockaddr swap fails here: the hook runs on the kernel’s own copy of the address it will actually connect to.',
    args: [{ key: 'remote_addr', kind: 'addr', label: 'remote addr' }] },
  { name: 'security_socket_bind', group: 'Network', risk: 'high',
    desc: 'LSM hook on bind — backdoor listeners.',
    backstops: ['bind'],
    toctou: 'The bound address/port in the event is the one the kernel used, immune to user-memory races.',
    args: [{ key: 'local_addr', kind: 'addr', label: 'local addr' }] },
  { name: 'security_socket_accept', group: 'Network', risk: 'medium',
    desc: 'LSM hook on accept — inbound connection on a listener.',
    backstops: ['accept', 'accept4'],
    toctou: 'Accepted peer observed from the kernel socket state.',
    args: [{ key: 'local_addr', kind: 'addr', label: 'local addr' }] },
  { name: 'security_socket_listen', group: 'Network', risk: 'medium',
    desc: 'LSM hook on listen — a socket entering the listening state.',
    backstops: ['listen'],
    toctou: 'Listening socket observed from kernel state, not the requested args.',
    args: [{ key: 'local_addr', kind: 'addr', label: 'local addr' },
           { key: 'backlog',    kind: 'num', label: 'backlog' }] },
  { name: 'security_socket_setsockopt', group: 'Network', risk: 'low',
    desc: 'LSM hook on setsockopt — promiscuous mode / raw-socket tuning.',
    backstops: ['setsockopt'],
    toctou: 'Option observed as applied by the kernel.',
    args: [{ key: 'level',   kind: 'num', label: 'level' },
           { key: 'optname', kind: 'num', label: 'optname' }] },

  { name: 'security_sb_mount', group: 'Kernel Surface', risk: 'high',
    desc: 'LSM hook on mount — more reliable than the mount syscall; host exposure / escape.',
    backstops: ['mount'],
    toctou: 'Mount observed at the superblock level with the real source/target.',
    args: [{ key: 'dev_name', kind: 'string', label: 'device' },
           { key: 'path',     kind: 'path', label: 'mount path' },
           { key: 'type',     kind: 'string', label: 'fs type' }] },
  { name: 'security_bpf', group: 'Kernel Surface', risk: 'high',
    desc: 'LSM hook on bpf() — eBPF program / map control plane.',
    backstops: ['bpf'],
    toctou: 'bpf command observed on the kernel-copied attribute union.',
    args: [{ key: 'cmd', kind: 'string', label: 'bpf cmd' }] },
  { name: 'security_bpf_map', group: 'Kernel Surface', risk: 'medium',
    desc: 'LSM hook on bpf map access — eBPF map read/write control.',
    backstops: ['bpf'],
    toctou: 'Map identity observed as the kernel resolved it.',
    args: [{ key: 'map_name', kind: 'string', label: 'map name' }] },
  { name: 'security_kernel_read_file', group: 'Kernel Surface', risk: 'high',
    desc: 'LSM hook when the kernel reads a file — module / firmware / kexec load.',
    backstops: ['finit_module', 'firmware load', 'kexec'],
    toctou: 'Module / firmware / kexec load observed on the exact file the kernel reads — fd or path swaps before load are irrelevant.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' },
           { key: 'type',     kind: 'string', label: 'read type' }] },
];

export const LSM_NAMES   = LSM_HOOKS.map(h => h.name);
export const LSM_BY_NAME = new Map(LSM_HOOKS.map(h => [h.name, h]));
export const LSM_GROUPS  = [...new Set(LSM_HOOKS.map(h => h.group))];
