export const TRACEPOINTS = [
  { name: 'sched_process_fork', group: 'Process Lifecycle', risk: 'high',
    desc: 'A process forked a child — the process tree / spawn edge.',
    args: [{ key: 'parent_comm', kind: 'string', label: 'parent comm' },
           { key: 'child_comm',  kind: 'string', label: 'child comm' }] },
  { name: 'sched_process_exec', group: 'Process Lifecycle', risk: 'high',
    desc: 'A process image was replaced via exec — the canonical "what ran" event.',
    args: [{ key: 'pathname', kind: 'path', label: 'binary path' }] },
  { name: 'sched_process_exit', group: 'Process Lifecycle', risk: 'low',
    desc: 'A process exited — pairs with fork/exec to close the lifecycle.',
    args: [{ key: 'exit_code', kind: 'num', label: 'exit code' }] },
  { name: 'task_rename', group: 'Process Lifecycle', risk: 'medium',
    desc: 'A task changed its comm name (task:task_rename) — process masquerading as a benign name.',
    args: [{ key: 'old_name', kind: 'string', label: 'old name' },
           { key: 'new_name', kind: 'string', label: 'new name' }] },

  { name: 'sched_switch', group: 'Scheduler', risk: 'low',
    desc: 'CPU switched tasks (sched:sched_switch) — pure scheduler, no syscall involved. ⚠ Fires on EVERY context switch: extremely high volume, scope it tightly (comm/pid) before enabling. Not in the default deployed policy.',
    args: [{ key: 'prev_comm', kind: 'string', label: 'prev comm' },
           { key: 'next_comm', kind: 'string', label: 'next comm' },
           { key: 'cpu',       kind: 'num',    label: 'cpu' }] },

  { name: 'module_load', group: 'Kernel Modules', risk: 'critical',
    desc: 'A kernel module was inserted — module-subsystem tracepoint, fires on any load path (init_module, finit_module, usermode helper).',
    args: [{ key: 'name',        kind: 'string', label: 'module name' },
           { key: 'pathname',    kind: 'path',   label: 'module path' },
           { key: 'version',     kind: 'string', label: 'version' },
           { key: 'src_version', kind: 'string', label: 'src version' }] },
  { name: 'module_free', group: 'Kernel Modules', risk: 'high',
    desc: 'A kernel module was unloaded (module:module_free) — rootkit covering its tracks.',
    args: [{ key: 'name',        kind: 'string', label: 'module name' },
           { key: 'version',     kind: 'string', label: 'version' },
           { key: 'src_version', kind: 'string', label: 'src version' }] },

  { name: 'cgroup_mkdir', group: 'Cgroups & Containers', risk: 'medium',
    desc: 'A cgroup directory was created (cgroup:cgroup_mkdir) — container creation; from inside a container it hints at escape staging (release_agent tricks).',
    args: [{ key: 'cgroup_path', kind: 'string', label: 'cgroup path' },
           { key: 'cgroup_id',   kind: 'num',    label: 'cgroup id' }] },
  { name: 'cgroup_rmdir', group: 'Cgroups & Containers', risk: 'low',
    desc: 'A cgroup directory was removed (cgroup:cgroup_rmdir) — container teardown.',
    args: [{ key: 'cgroup_path', kind: 'string', label: 'cgroup path' },
           { key: 'cgroup_id',   kind: 'num',    label: 'cgroup id' }] },
  { name: 'cgroup_attach_task', group: 'Cgroups & Containers', risk: 'high',
    desc: 'A task was attached to a cgroup (cgroup:cgroup_attach_task) — process moved between containers / escape & lateral movement indicator.',
    args: [{ key: 'cgroup_path', kind: 'string', label: 'cgroup path' },
           { key: 'comm',        kind: 'string', label: 'comm' },
           { key: 'pid',         kind: 'num',    label: 'pid' }] },
];

export const TRACEPOINT_NAMES   = TRACEPOINTS.map(t => t.name);
export const TRACEPOINT_GROUPS  = [...new Set(TRACEPOINTS.map(t => t.group))];
