export const SYSCALL_EVENTS = [
  { name: 'execve', group: 'Process Lifecycle', risk: 'high',
    desc: 'execve syscall — run a new program by path with argv/envp.',
    args: [{ key: 'pathname', kind: 'path', label: 'binary path' },
           { key: 'argv',     kind: 'string', label: 'argv substring' }] },
  { name: 'execveat', group: 'Process Lifecycle', risk: 'high',
    desc: 'execve relative to a directory fd — exec of a path resolved from an fd.',
    args: [{ key: 'pathname', kind: 'path', label: 'binary path' }] },
  { name: 'clone', group: 'Process Lifecycle', risk: 'medium',
    desc: 'Create a new process/thread — clone flags reveal namespace/escape intent.',
    args: [{ key: 'flags', kind: 'string', label: 'clone flags' }] },

  { name: 'open', group: 'File & Path', risk: 'medium',
    desc: 'Open a file by path — sensitive-path access.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' },
           { key: 'flags',    kind: 'string', label: 'open flags' }] },
  { name: 'openat', group: 'File & Path', risk: 'medium',
    desc: 'Open a file relative to a directory fd.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' },
           { key: 'flags',    kind: 'string', label: 'open flags' }] },
  { name: 'openat2', group: 'File & Path', risk: 'medium',
    desc: 'Open with extended how-flags (resolve restrictions).',
    args: [{ key: 'pathname', kind: 'path', label: 'path' }] },
  { name: 'chdir', group: 'File & Path', risk: 'low',
    desc: 'Change working directory — context for relative-path resolution.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' }] },
  { name: 'chroot', group: 'File & Path', risk: 'high',
    desc: 'Change apparent root directory — container-escape primitive.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' }] },

  { name: 'ptrace', group: 'Privilege & Escape', risk: 'high',
    desc: 'Attach to / inspect another process — debuggers and code injection.',
    args: [{ key: 'request', kind: 'string', label: 'ptrace request' },
           { key: 'pid',     kind: 'num', label: 'target pid' }] },
  { name: 'kill', group: 'Privilege & Escape', risk: 'medium',
    desc: 'Send a signal to a process — tampering / defense evasion.',
    args: [{ key: 'pid', kind: 'num', label: 'target pid' },
           { key: 'sig', kind: 'num', label: 'signal' }] },
  { name: 'mount', group: 'Privilege & Escape', risk: 'high',
    desc: 'Mount a filesystem — host path exposure / escape.',
    args: [{ key: 'source',         kind: 'path', label: 'source' },
           { key: 'target',         kind: 'path', label: 'target' },
           { key: 'filesystemtype', kind: 'string', label: 'fs type' }] },
  { name: 'setns', group: 'Privilege & Escape', risk: 'high',
    desc: 'Join an existing namespace — cross-namespace access / escape.',
    args: [{ key: 'flags', kind: 'string', label: 'ns flags' }] },

  { name: 'socket', group: 'Network', risk: 'medium',
    desc: 'Create a network socket — outbound connections / C2.',
    args: [{ key: 'domain', kind: 'string', label: 'domain' },
           { key: 'type',   kind: 'string', label: 'type' }] },
  { name: 'connect', group: 'Network', risk: 'medium',
    desc: 'Initiate an outbound connection to a remote host.',
    args: [{ key: 'addr', kind: 'addr', label: 'remote addr' }] },
  { name: 'bind', group: 'Network', risk: 'medium',
    desc: 'Bind a socket to a port — listeners / backdoors.',
    args: [{ key: 'addr', kind: 'addr', label: 'local addr' }] },

  { name: 'memfd_create', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Create an anonymous in-memory file — fileless malware staging.',
    args: [{ key: 'name',  kind: 'string', label: 'name' },
           { key: 'flags', kind: 'string', label: 'flags' }] },
  { name: 'unshare', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Detach into new namespaces — privilege/namespace manipulation.',
    args: [{ key: 'flags', kind: 'string', label: 'ns flags' }] },
];

export const SYSCALL_EVENT_NAMES  = SYSCALL_EVENTS.map(s => s.name);
export const SYSCALL_EVENT_GROUPS = [...new Set(SYSCALL_EVENTS.map(s => s.group))];
