export const SYSCALL_EVENTS = [
  { name: 'execve', group: 'Process Lifecycle', risk: 'high',
    desc: 'execve syscall — run a new program by path with argv/envp.',
    args: [{ key: 'pathname', kind: 'path', label: 'binary path' },
           { key: 'argv',     kind: 'string', label: 'argv substring' }] },
  { name: 'execveat', group: 'Process Lifecycle', risk: 'high',
    desc: 'execve relative to a directory fd — exec of a path resolved from an fd.',
    args: [{ key: 'pathname', kind: 'path', label: 'binary path' }] },
  { name: 'clone', group: 'Process Lifecycle', risk: 'medium',
    desc: 'Create a new process/thread — clone flags reveal namespace/escape intent.',
    args: [{ key: 'flags', kind: 'string', label: 'clone flags' }] },
  { name: 'process_vm_writev', group: 'Process Lifecycle', risk: 'critical',
    desc: 'Write memory into another process — code injection primitive.',
    args: [{ key: 'pid', kind: 'num', label: 'target pid' }] },

  { name: 'open', group: 'File & Path', risk: 'medium',
    desc: 'Open a file by path — sensitive-path access.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' },
           { key: 'flags',    kind: 'string', label: 'open flags' }] },
  { name: 'openat', group: 'File & Path', risk: 'medium',
    desc: 'Open a file relative to a directory fd.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' },
           { key: 'flags',    kind: 'string', label: 'open flags' }] },
  { name: 'openat2', group: 'File & Path', risk: 'medium',
    desc: 'Open with extended how-flags (resolve restrictions).',
    args: [{ key: 'pathname', kind: 'path', label: 'path' }] },
  { name: 'chdir', group: 'File & Path', risk: 'low',
    desc: 'Change working directory — context for relative-path resolution.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' }] },
  { name: 'chroot', group: 'File & Path', risk: 'high',
    desc: 'Change apparent root directory — container-escape primitive.',
    args: [{ key: 'pathname', kind: 'path', label: 'path' }] },

  { name: 'ptrace', group: 'Privilege & Escape', risk: 'high',
    desc: 'Attach to / inspect another process — debuggers and code injection.',
    args: [{ key: 'request', kind: 'string', label: 'ptrace request' },
           { key: 'pid',     kind: 'num', label: 'target pid' }] },
  { name: 'kill', group: 'Privilege & Escape', risk: 'medium',
    desc: 'Send a signal to a process — tampering / defense evasion.',
    args: [{ key: 'pid', kind: 'num', label: 'target pid' },
           { key: 'sig', kind: 'num', label: 'signal' }] },
  { name: 'mount', group: 'Privilege & Escape', risk: 'high',
    desc: 'Mount a filesystem — host path exposure / escape.',
    args: [{ key: 'source',         kind: 'path', label: 'source' },
           { key: 'target',         kind: 'path', label: 'target' },
           { key: 'filesystemtype', kind: 'string', label: 'fs type' }] },
  { name: 'setns', group: 'Privilege & Escape', risk: 'high',
    desc: 'Join an existing namespace — cross-namespace access / escape.',
    args: [{ key: 'flags', kind: 'string', label: 'ns flags' }] },
  { name: 'pivot_root', group: 'Privilege & Escape', risk: 'critical',
    desc: 'Change the process root filesystem — container escape primitive.',
    args: [{ key: 'new_root', kind: 'path', label: 'new root' }] },
  { name: 'umount2', group: 'Privilege & Escape', risk: 'high',
    desc: 'Unmount a filesystem — isolation and defense-evasion operation.',
    args: [{ key: 'target', kind: 'path', label: 'mountpoint' }] },
  { name: 'setuid', group: 'Privilege & Escape', risk: 'high',
    desc: 'Change the process UID.',
    args: [{ key: 'uid', kind: 'num', label: 'uid' }] },
  { name: 'setgid', group: 'Privilege & Escape', risk: 'high',
    desc: 'Change the process GID.',
    args: [{ key: 'gid', kind: 'num', label: 'gid' }] },
  { name: 'setreuid', group: 'Privilege & Escape', risk: 'high',
    desc: 'Change real and effective UID values.',
    args: [{ key: 'ruid', kind: 'num', label: 'real uid' }, { key: 'euid', kind: 'num', label: 'effective uid' }] },
  { name: 'setresuid', group: 'Privilege & Escape', risk: 'high',
    desc: 'Change real, effective, and saved UID values.',
    args: [{ key: 'ruid', kind: 'num', label: 'real uid' }, { key: 'euid', kind: 'num', label: 'effective uid' }, { key: 'suid', kind: 'num', label: 'saved uid' }] },
  { name: 'setresgid', group: 'Privilege & Escape', risk: 'high',
    desc: 'Change real, effective, and saved GID values.',
    args: [{ key: 'rgid', kind: 'num', label: 'real gid' }, { key: 'egid', kind: 'num', label: 'effective gid' }, { key: 'sgid', kind: 'num', label: 'saved gid' }] },
  { name: 'capset', group: 'Privilege & Escape', risk: 'high',
    desc: 'Change Linux process capabilities.',
    args: [{ key: 'pid', kind: 'num', label: 'target pid' }] },

  { name: 'socket', group: 'Network', risk: 'medium',
    desc: 'Create a network socket — outbound connections / C2.',
    args: [{ key: 'domain', kind: 'string', label: 'domain' },
           { key: 'type',   kind: 'string', label: 'type' }] },
  { name: 'connect', group: 'Network', risk: 'medium',
    desc: 'Initiate an outbound connection to a remote host.',
    args: [{ key: 'addr', kind: 'addr', label: 'remote addr' }] },
  { name: 'bind', group: 'Network', risk: 'medium',
    desc: 'Bind a socket to a port — listeners / backdoors.',
    args: [{ key: 'addr', kind: 'addr', label: 'local addr' }] },
  { name: 'accept', group: 'Network', risk: 'medium',
    desc: 'Accept an incoming connection on a listening socket.',
    args: [{ key: 'fd', kind: 'num', label: 'socket fd' }] },
  { name: 'accept4', group: 'Network', risk: 'medium',
    desc: 'Accept an incoming connection with flags.',
    args: [{ key: 'fd', kind: 'num', label: 'socket fd' }, { key: 'flags', kind: 'string', label: 'flags' }] },
  { name: 'dup2', group: 'Network', risk: 'high',
    desc: 'Duplicate a file descriptor — stdin/stdout/stderr redirection.',
    args: [{ key: 'oldfd', kind: 'num', label: 'old fd' }, { key: 'newfd', kind: 'num', label: 'new fd' }] },
  { name: 'dup3', group: 'Network', risk: 'high',
    desc: 'Duplicate a file descriptor with flags.',
    args: [{ key: 'oldfd', kind: 'num', label: 'old fd' }, { key: 'newfd', kind: 'num', label: 'new fd' }, { key: 'flags', kind: 'string', label: 'flags' }] },

  { name: 'memfd_create', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Create an anonymous in-memory file — fileless malware staging.',
    args: [{ key: 'name',  kind: 'string', label: 'name' },
           { key: 'flags', kind: 'string', label: 'flags' }] },
  { name: 'unshare', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Detach into new namespaces — privilege/namespace manipulation.',
    args: [{ key: 'flags', kind: 'string', label: 'ns flags' }] },
  { name: 'bpf', group: 'Fileless & Namespaces', risk: 'critical',
    desc: 'Load or manipulate eBPF programs and maps.',
    args: [{ key: 'cmd', kind: 'num', label: 'BPF command' }] },
  { name: 'io_uring_setup', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Create an io_uring instance that can bypass per-syscall monitoring.',
    args: [{ key: 'entries', kind: 'num', label: 'entries' }] },
  { name: 'io_uring_enter', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Submit or wait for asynchronous io_uring operations.',
    args: [{ key: 'fd', kind: 'num', label: 'ring fd' }] },
  { name: 'io_uring_register', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Register buffers or files for asynchronous io_uring operations.',
    args: [{ key: 'fd', kind: 'num', label: 'ring fd' }, { key: 'opcode', kind: 'num', label: 'register opcode' }] },
  { name: 'mmap', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Create a memory mapping with executable or writable protection.',
    args: [{ key: 'prot', kind: 'num', label: 'protection flags' }] },
  { name: 'mprotect', group: 'Fileless & Namespaces', risk: 'high',
    desc: 'Change memory protections, including W|X transitions.',
    args: [{ key: 'prot', kind: 'num', label: 'protection flags' }] },
  { name: 'init_module', group: 'Fileless & Namespaces', risk: 'critical',
    desc: 'Load a kernel module from memory.',
    args: [{ key: 'image', kind: 'string', label: 'module image' }] },
  { name: 'finit_module', group: 'Fileless & Namespaces', risk: 'critical',
    desc: 'Load a kernel module from a file descriptor.',
    args: [{ key: 'fd', kind: 'num', label: 'module fd' }] },
];

export const SYSCALL_EVENT_NAMES  = SYSCALL_EVENTS.map(s => s.name);
export const SYSCALL_EVENT_GROUPS = [...new Set(SYSCALL_EVENTS.map(s => s.group))];
