
export const CONTAINER_PATH_PRESETS = [
  { group: 'Secrets & credentials', paths: [
    { value: '/etc/shadow',        desc: 'Password hashes' },
    { value: '/etc/passwd',        desc: 'User accounts' },
    { value: '/etc/sudoers',       desc: 'Sudo rights — privilege escalation' },
    { value: '/var/run/secrets/*', desc: 'K8s service-account tokens' },
    { value: '/run/secrets/*',     desc: 'K8s secrets (alternative path)' },
    { value: '/root/.ssh/*',       desc: 'Root SSH keys' },
    { value: '/.ssh/*',            desc: 'SSH keys anywhere in the tree' },
  ] },
  { group: 'Config & cron', paths: [
    { value: '/etc/*',             desc: 'Any system configuration file' },
    { value: '/etc/crontab',       desc: 'System cron table — persistence' },
    { value: '/etc/cron.d/*',      desc: 'Cron drop-ins — persistence' },
    { value: '/etc/ld.so.preload', desc: 'Library preload — userland rootkit' },
  ] },
  { group: 'Binaries', paths: [
    { value: '/bin/*',           desc: 'System binaries — tamper / trojan' },
    { value: '/sbin/*',          desc: 'Admin binaries' },
    { value: '/usr/bin/*',       desc: 'User binaries' },
    { value: '/usr/sbin/*',      desc: 'Admin binaries (usr)' },
    { value: '/usr/local/bin/*', desc: 'Locally installed binaries' },
  ] },
  { group: 'Writable staging', paths: [
    { value: '/tmp/*',     desc: 'World-writable temp — payload staging' },
    { value: '/dev/shm/*', desc: 'Shared memory — fileless staging' },
    { value: '/var/tmp/*', desc: 'Persistent temp — staging that survives reboot' },
  ] },
  { group: 'Proc & anti-forensics', paths: [
    { value: '/proc/*/mem',  desc: 'Process memory — injection / credential reads' },
    { value: '/proc/*/root', desc: 'Other task root — escape reconnaissance' },
    { value: '/proc/sys/*',  desc: 'Kernel tunables' },
    { value: '/var/log/*',   desc: 'Logs — wiping / tampering' },
  ] },
  { group: 'Home & roots', paths: [
    { value: '/root/*', desc: 'Root home directory' },
    { value: '/home/*', desc: 'User home directories' },
  ] },
];

export const SCOPE_FIELDS = [
  { key: 'container',  kind: 'flag',   label: 'container',  hint: 'only containerized tasks (recommended)' },
  { key: 'comm',       kind: 'string', label: 'comm',       hint: 'process name, e.g. nginx' },
  { key: 'executable', kind: 'path',   label: 'executable', hint: 'binary path, e.g. /usr/bin/curl' },
  { key: 'uid',        kind: 'num',    label: 'uid',         hint: 'user id, e.g. 0' },
  { key: 'pid',        kind: 'num',    label: 'pid',         hint: 'process id' },
  { key: 'cgroup_id',  kind: 'num',    label: 'cgroup_id',  hint: 'numeric cgroup id' },
];

const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export function genPolicyYaml(title, events, scope) {
  const scopeLines = [];
  if (scope.container !== false) scopeLines.push('    - container');
  for (const f of SCOPE_FIELDS) {
    if (f.kind === 'flag') continue;
    const v = (scope[f.key] || '').trim();
    if (v) scopeLines.push(`    - ${f.key}=${v}`);
  }
  if (scopeLines.length === 0) scopeLines.push('    - container');

  const ruleLines = [];
  for (const ev of events) {
    ruleLines.push(`    - event: ${ev.name}`);
    const fs = (ev.filters || []).filter(f => (f.value || '').trim() !== '');
    if (fs.length) {
      ruleLines.push('      filters:');
      for (const f of fs) ruleLines.push(`        - args.${f.key}=${f.value.trim()}`);
    }
  }
  if (ruleLines.length === 0) {
    ruleLines.push('    # (no events added yet — use the + button to add hooks to this policy)');
  }

  return [
    `# Tracee policy — generated by kvisior ${title} builder`,
    `# Apply: merge spec.scope + spec.rules into helm/templates/tracee.yaml,`,
    `# commit, and redeploy Tracee. Filtering happens in-kernel at the eBPF layer.`,
    'apiVersion: tracee.aquasec.com/v1beta1',
    'kind: Policy',
    'metadata:',
    `  name: wolfee-watcher-${slug(title)}`,
    'spec:',
    '  scope:',
    ...scopeLines,
    '  rules:',
    ...ruleLines,
    '',
  ].join('\n');
}

export function countFilters(filters) {
  return (filters || []).filter(f => (f.value || '').trim() !== '').length;
}
